baseURL = "https://hamid-kord.ir/"
languageCode = "fa-ir"
defaultContentLanguage = "fa-ir"
languageDirection = "rtl"
title = "حمید کرد"
theme = "m10c"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "برچسب ها"
    url = "/tags/"
    weight = 1
    [menu.main.params]
      icon = "tag"

  [[menu.main]]
    identifier = "RSS"
    name = "فید RSS"
    url = "/index.xml"
    weight = 2
    [menu.main.params]
      icon = "rss"

[params]
    author = "حمید کرد"
    Description = "وبلاگ شخصی حمید کرد، توسعه دهنده نرم افزار، علاقه مند به موضوعات مربوط به دنیای فناوری"
    EnableTwitterEmbed = true
    # avatar = "test.jpg"
    # favicon = "ttt.jpg"
    menu_item_separator = " | "
    
    graphcommentId = "hamid-kord"

    [[params.social]]
        icon = "github"
        name = "گیتهاب حمید کرد"
        url = "https://github.com/mer30hamid"
    [[params.social]]
        icon = "cloud"
        name = "بلواسکای حمید کرد"
        url = "https://staging.bsky.app/profile/hamid-kord.ir"
    # [[params.social]]
    #     icon = "layers"
    #     name = "استک اورفلو حمید کرد"
    #     url = "https://stackoverflow.com/users/1379624/hamid-kurd"
    [[params.social]]
        icon = "linkedin"
        name = "لینکداین حمید کرد"
        url = "https://www.linkedin.com/in/hamid-kord/"
    # [[params.social]]
    #     icon = "hash"
    #     name = "هشنود حمید کرد"
    #     url = "https://hn.hamid-kord.ir/"
    [[params.social]]
        icon = "twitter"
        name = "توییتر حمید کرد"
        url = "https://twitter.com/mer30hamid"
        
[markup.goldmark.renderer]
  unsafe= true

[markup.highlight]
  #style = 'monokai'
  #style = 'rrt'
  #style = 'xcode-dark'
  #style = 'fruity'
  style = 'dracula'

# [params.style]
#   darkestColor = "#181F1C"
#   darkColor = "#274029"
#   lightColor = "#BFD1E5"
#   lightestColor = "#EEEEEE"
#   primaryColor = "#73E2A7"
  
#[params.style]
#  darkestColor = "#383F17"
#  darkColor = "#6A4A23"
#  lightColor = "#E0C14F"
#  lightestColor = "#FBD19D"
#  primaryColor = "#FFF"
  
#[params.style]
#  darkestColor = "#515A47"
#  darkColor = "#050517"
#  lightestColor = "#FEFCFB"
#  
#  lightColor = "#AFE"
#  primaryColor = "#AFF"

#[params.style]
  #primaryColor = "#57cc8a"
  #lightColor = "#57cc8a"

[params.csp]
  childsrc = ["'self'"]
  fontsrc = ["'self'",
    "https://use.fontawesome.com",
    "https://fonts.gstatic.com",
    "https://public.slidesharecdn.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
  formaction = ["'self'",
    "https://syndication.twitter.com/",
    "https://platform.twitter.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"]
  framesrc = ["'self'",
    "www.youtube.com",
    "www.youtube-nocookie.com",
    "https://platform.twitter.com",
    "https://syndication.twitter.com",
    "https://jsfiddle.net",
    "fiddle.jshell.net",
    "*.jsfiddle.net",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com",
    "*.graphcomment.com",
    "graphcomment.com"]
  imgsrc = ["'self'",
    "https://www.google-analytics.com",
    "https://platform.twitter.com",
    "*.twimg.com",
    "https://syndication.twitter.com",
    "data:",
    "https://files.kuula.io",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com"
    ]
  objectsrc = ["'none'"]
  stylesrc = ["'self'",
    "'unsafe-inline'",
    "https://use.fontawesome.com",
    "https://fonts.googleapis.com",
    "https://www.google.com",
    "https://platform.twitter.com",
    "*.twimg.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com",
    "*.jsdelivr.net"
    ]
  scriptsrc = ["'self'",
    "'unsafe-inline'",
    "https://platform.twitter.com",
    "https://cdn.syndication.twimg.com",
    "*.amazon-adsystem.com",
    "https://www.google-analytics.com",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com",
    "*.graphcomment.com",
    "*.jsdelivr.net"
    ]
  connectsrc = ["'self'",
    "disqus.com",
    "disquscdn.com",
    "*.disqus.com",
    "*.disquscdn.com",
    "*.graphcomment.com",
    "graphcomment.com"]